export const CREATE_TEST_REQUEST = "CREATE_TEST_REQUEST";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";
export const CREATE_TEST_FAILURE = "CREATE_TEST_FAILURE";

export const GET_ALL_TESTS_REQUEST = "GET_ALL_TESTS_REQUEST";
export const GET_ALL_TESTS_SUCCESS = "GET_ALL_TESTS_SUCCESS";
export const GET_ALL_TESTS_FAILURE = "GET_ALL_TESTS_FAILURE";

export const GET_TEST_BY_PLANET_ID_REQUEST = "GET_TEST_BY_PLANET_ID_REQUEST";
export const GET_TEST_BY_PLANET_ID_SUCCESS = "GET_TEST_BY_PLANET_ID_SUCCESS";
export const GET_TEST_BY_PLANET_ID_FAILURE = "GET_TEST_BY_PLANET_ID_FAILURE";

export const GET_TEST_BY_SUBTOPIC_REQUEST = "GET_TEST_BY_SUBTOPIC_REQUEST";
export const GET_TEST_BY_SUBTOPIC_SUCCESS = "GET_TEST_BY_SUBTOPIC_SUCCESS";
export const GET_TEST_BY_SUBTOPIC_FAILURE = "GET_TEST_BY_SUBTOPIC_FAILURE";

export const UPDATE_TEST_REQUEST = "UPDATE_TEST_REQUEST";
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";
export const UPDATE_TEST_FAILURE = "UPDATE_TEST_FAILURE";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_FAILURE = "DELETE_TEST_FAILURE";

export const ADD_QUESTION_ANSWERS_REQUEST = "ADD_QUESTION_ANSWERS_REQUEST";
export const ADD_QUESTION_ANSWERS_SUCCESS = "ADD_QUESTION_ANSWERS_SUCCESS";
export const ADD_QUESTION_ANSWERS_FAILURE = "ADD_QUESTION_ANSWERS_FAILURE";

export const GET_TEST_WITH_QUESTIONS_REQUEST = "GET_TEST_WITH_QUESTIONS_REQUEST";
export const GET_TEST_WITH_QUESTIONS_SUCCESS = "GET_TEST_WITH_QUESTIONS_SUCCESS";
export const GET_TEST_WITH_QUESTIONS_FAILURE = "GET_TEST_WITH_QUESTIONS_FAILURE";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAILURE = "DELETE_QUESTION_FAILURE";

export const START_TEST_REQUEST = "START_TEST_REQUEST";
export const START_TEST_SUCCESS = "START_TEST_SUCCESS";
export const START_TEST_FAILURE = "START_TEST_FAILURE";

export const COMPLETE_TEST_REQUEST = "COMPLETE_TEST_REQUEST";
export const COMPLETE_TEST_SUCCESS = "COMPLETE_TEST_SUCCESS";
export const COMPLETE_TEST_FAILURE = "COMPLETE_TEST_FAILURE";

export const CLEAR_ERRORS_REQUEST = "CLEAR_ERRORS_REQUEST";
export const SET_TEST_AFTER_ACCEPT_INVITATION = "SET_TEST_AFTER_ACCEPT_INVITATION";
export const SET_BATTLE_ID = "SET_BATTLE_ID";

export const SET_SELECTED_TEST = "SET_SELECTED_TEST";
export const RESET_SELECTED_TEST = "RESET_SELECTED_TEST";