export const CREATE_PLANET_REQUEST = "CREATE_PLANET_REQUEST";
export const CREATE_PLANET_SUCCESS = "CREATE_PLANET_SUCCESS";
export const CREATE_PLANET_FAILURE = "CREATE_PLANET_FAILURE";

export const GET_ALL_PLANETS_REQUEST = "GET_ALL_PLANETS_REQUEST";
export const GET_ALL_PLANETS_SUCCESS = "GET_ALL_PLANETS_SUCCESS";
export const GET_ALL_PLANETS_FAILURE = "GET_ALL_PLANETS_FAILURE";

export const GET_PLANET_REQUEST = "GET_PLANET_REQUEST";
export const GET_PLANET_SUCCESS = "GET_PLANET_SUCCESS";
export const GET_PLANET_FAILURE = "GET_PLANET_FAILURE";

export const GET_ALL_PLANET_TOPICS_REQUEST = "GET_ALL_PLANET_TOPICS_REQUEST";
export const GET_ALL_PLANET_TOPICS_SUCCESS = "GET_ALL_PLANET_TOPICS_SUCCESS";
export const GET_ALL_PLANET_TOPICS_FAILURE = "GET_ALL_PLANET_TOPICS_FAILURE";

export const GET_ALL_PLANET_SUBTOPICS_REQUEST = "GET_ALL_PLANET_SUBTOPICS_REQUEST";
export const GET_ALL_PLANET_SUBTOPICS_SUCCESS = "GET_ALL_PLANET_SUBTOPICS_SUCCESS";
export const GET_ALL_PLANET_SUBTOPICS_FAILURE = "GET_ALL_PLANET_SUBTOPICS_FAILURE";

export const DELETE_PLANET_REQUEST = "DELETE_PLANET_REQUEST";
export const DELETE_PLANET_SUCCESS = "DELETE_PLANET_SUCCESS";
export const DELETE_PLANET_FAILURE = "DELETE_PLANET_FAILURE";

export const UPDATE_PLANET_REQUEST = "UPDATE_PLANET_REQUEST";
export const UPDATE_PLANET_SUCCESS = "UPDATE_PLANET_SUCCESS";
export const UPDATE_PLANET_FAILURE = "UPDATE_PLANET_FAILURE";

export const CLEAR_ERRORS_REQUEST = "CLEAR_ERRORS_REQUEST";