export const GET_ALL_THEORIES_REQUEST = "GET_ALL_THEORIES_REQUEST";
export const GET_ALL_THEORIES_SUCCESS = "GET_ALL_THEORIES_SUCCESS";
export const GET_ALL_THEORIES_FAILURE = "GET_ALL_THEORIES_FAILURE";

export const GET_THEORY_BY_ID_REQUEST = "GET_THEORY_BY_ID_REQUEST";
export const GET_THEORY_BY_ID_SUCCESS = "GET_THEORY_BY_ID_SUCCESS";
export const GET_THEORY_BY_ID_FAILURE = "GET_THEORY_BY_ID_FAILURE";

export const GET_THEORY_BY_PLANET_ID_REQUEST = "GET_THEORY_BY_PLANET_ID_REQUEST";
export const GET_THEORY_BY_PLANET_ID_SUCCESS = "GET_THEORY_BY_PLANET_ID_SUCCESS";
export const GET_THEORY_BY_PLANET_ID_FAILURE = "GET_THEORY_BY_PLANET_ID_FAILURE";

export const CREATE_THEORY_REQUEST = "CREATE_THEORY_REQUEST";
export const CREATE_THEORY_SUCCESS = "CREATE_THEORY_SUCCESS";
export const CREATE_THEORY_FAILURE = "CREATE_THEORY_FAILURE";

export const UPDATE_THEORY_REQUEST = "UPDATE_THEORY_REQUEST";
export const UPDATE_THEORY_SUCCESS = "UPDATE_THEORY_SUCCESS";
export const UPDATE_THEORY_FAILURE = "UPDATE_THEORY_FAILURE";

export const DELETE_THEORY_REQUEST = "DELETE_THEORY_REQUEST";
export const DELETE_THEORY_SUCCESS = "DELETE_THEORY_SUCCESS";
export const DELETE_THEORY_FAILURE = "DELETE_THEORY_FAILURE";