export const GET_ALL_MATERIALS_REQUEST = "GET_ALL_MATERIALS_REQUEST";
export const GET_ALL_MATERIALS_SUCCESS = "GET_ALL_MATERIALS_SUCCESS";
export const GET_ALL_MATERIALS_FAILURE = "GET_ALL_MATERIALS_FAILURE";

export const GET_ALL_MATERIAL_TYPES_REQUEST = "GET_ALL_MATERIAL_TYPES_REQUEST";
export const GET_ALL_MATERIAL_TYPES_SUCCESS = "GET_ALL_MATERIAL_TYPES_SUCCESS";
export const GET_ALL_MATERIAL_TYPES_FAILURE = "GET_ALL_MATERIAL_TYPES_FAILURE";

export const GET_ALL_MATERIAL_THEMES_REQUEST = "GET_ALL_MATERIAL_THEMES_REQUEST";
export const GET_ALL_MATERIAL_THEMES_SUCCESS = "GET_ALL_MATERIAL_THEMES_SUCCESS";
export const GET_ALL_MATERIAL_THEMES_FAILURE = "GET_ALL_MATERIAL_THEMES_FAILURE";

export const CREATE_MATERIAL_REQUEST = "CREATE_MATERIAL_REQUEST";
export const CREATE_MATERIAL_SUCCESS = "CREATE_MATERIAL_SUCCESS";
export const CREATE_MATERIAL_FAILURE = "CREATE_MATERIAL_FAILURE";

export const UPDATE_MATERIAL_REQUEST = "UPDATE_MATERIAL_REQUEST";
export const UPDATE_MATERIAL_SUCCESS = "UPDATE_MATERIAL_SUCCESS";
export const UPDATE_MATERIAL_FAILURE = "UPDATE_MATERIAL_FAILURE";

export const DELETE_MATERIAL_REQUEST = "DELETE_MATERIAL_REQUEST";
export const DELETE_MATERIAL_SUCCESS = "DELETE_MATERIAL_SUCCESS";
export const DELETE_MATERIAL_FAILURE = "DELETE_MATERIAL_FAILURE";

export const EXTRACT_VIDEO_ID_BY_URL_REQUEST = "EXTRACT_VIDEO_ID_BY_URL_REQUEST";
export const EXTRACT_VIDEO_ID_BY_URL_SUCCESS = "EXTRACT_VIDEO_ID_BY_URL_SUCCESS";
export const EXTRACT_VIDEO_ID_BY_URL_FAILURE = "EXTRACT_VIDEO_ID_BY_URL_FAILURE";