export const GET_IMAGE_BY_ID_REQUEST = "GET_IMAGE_BY_ID_REQUEST";
export const GET_IMAGE_BY_ID_SUCCESS = "GET_IMAGE_BY_ID_SUCCESS";
export const GET_IMAGE_BY_ID_FAILURE = "GET_IMAGE_BY_ID_FAILURE";

export const SET_IMAGE_BASE64 = "SET_IMAGE_BASE64";