export const RUN_CODE_REQUEST = "RUN_CODE_REQUEST";
export const RUN_CODE_SUCCESS = "RUN_CODE_SUCCESS";
export const RUN_CODE_FAILURE = "RUN_CODE_FAILURE";

export const RUN_LAB4_CODE_REQUEST = "RUN_LAB4_CODE_REQUEST";
export const RUN_LAB4_CODE_SUCCESS = "RUN_LAB4_CODE_SUCCESS";
export const RUN_LAB4_CODE_FAILURE = "RUN_LAB4_CODE_FAILURE";

export const RUN_LAB1_CODE_REQUEST = "RUN_LAB1_CODE_REQUEST";
export const RUN_LAB1_CODE_SUCCESS = "RUN_LAB1_CODE_SUCCESS";
export const RUN_LAB1_CODE_FAILURE = "RUN_LAB1_CODE_FAILURE";

export const RUN_LAB3_CODE_REQUEST = "RUN_LAB3_CODE_REQUEST";
export const RUN_LAB3_CODE_SUCCESS = "RUN_LAB3_CODE_SUCCESS";
export const RUN_LAB3_CODE_FAILURE = "RUN_LAB3_CODE_FAILURE";

export const RUN_LAB5_CODE_REQUEST = "RUN_LAB5_CODE_REQUEST";
export const RUN_LAB5_CODE_SUCCESS = "RUN_LAB5_CODE_SUCCESS";
export const RUN_LAB5_CODE_FAILURE = "RUN_LAB5_CODE_FAILURE";

export const TEST_CODE_REQUEST = "TEST_CODE_REQUEST";
export const TEST_CODE_SUCCESS = "TEST_CODE_SUCCESS";
export const TEST_CODE_FAILURE = "TEST_CODE_FAILURE";

export const CLEAR_OUTPUT = "CLEAR_OUTPUT";