export const GET_ALL_AVATARS_REQUEST = "GET_ALL_AVATARS_REQUEST";
export const GET_ALL_AVATARS_SUCCESS = "GET_ALL_AVATARS_SUCCESS";
export const GET_ALL_AVATARS_FAILURE = "GET_ALL_AVATARS_FAILURE";

export const GET_USER_PURCHASES_REQUEST = "GET_USER_PURCHASES_REQUEST";
export const GET_USER_PURCHASES_SUCCESS = "GET_USER_PURCHASES_SUCCESS";
export const GET_USER_PURCHASES_FAILURE = "GET_USER_PURCHASES_FAILURE";

export const CREATE_AVATAR_REQUEST = "CREATE_AVATAR_REQUEST";
export const CREATE_AVATAR_SUCCESS = "CREATE_AVATAR_SUCCESS";
export const CREATE_AVATAR_FAILURE = "CREATE_AVATAR_FAILURE";

export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAILURE = "UPDATE_AVATAR_FAILURE";

export const DELETE_AVATAR_REQUEST = "DELETE_AVATAR_REQUEST";
export const DELETE_AVATAR_SUCCESS = "DELETE_AVATAR_SUCCESS";
export const DELETE_AVATAR_FAILURE = "DELETE_AVATAR_FAILURE";
