export const CREATE_CASE_REQUEST = "CREATE_CASE_REQUEST";
export const CREATE_CASE_SUCCESS = "CREATE_CASE_SUCCESS";
export const CREATE_CASE_FAILURE = "CREATE_CASE_FAILURE";

export const GET_ALL_CASES_REQUEST = "GET_ALL_CASES_REQUEST";
export const GET_ALL_CASES_SUCCESS = "GET_ALL_CASES_SUCCESS";
export const GET_ALL_CASES_FAILURE = "GET_ALL_CASES_FAILURE";

export const UPDATE_CASE_REQUEST = "UPDATE_CASE_REQUEST";
export const UPDATE_CASE_SUCCESS = "UPDATE_CASE_SUCCESS";
export const UPDATE_CASE_FAILURE = "UPDATE_CASE_FAILURE";

export const DELETE_CASE_REQUEST = "DELETE_CASE_REQUEST";
export const DELETE_CASE_SUCCESS = "DELETE_CASE_SUCCESS";
export const DELETE_CASE_FAILURE = "DELETE_CASE_FAILURE";